version: '3.1'

services:
  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: esportAppDB
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
    volumes:
      - ./mysql_data:/var/lib/mysql